import { User, Course, AttendanceSession, Attendance } from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'user-student-1',
    name: 'นายสมชาย ใจดี',
    studentId: '6501234567',
    email: 'student@example.com',
    role: 'student',
    department: 'วิศวกรรมคอมพิวเตอร์',
    profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-teacher-1',
    name: 'ดร. โรเบิร์ต แวนซ์',
    email: 'teacher@example.com',
    role: 'teacher',
    department: 'สาขาวิชาวิทยาการคอมพิวเตอร์',
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
  }
];

export const INITIAL_COURSES: Course[] = [
  {
    id: 'course-1',
    name: 'Mobile Application Development',
    code: 'CPE401',
    teacherId: 'user-teacher-1',
    teacherName: 'ดร. โรเบิร์ต แวนซ์',
    room: 'ห้อง 301',
    schedule: '09:00 - 12:00',
    enrolledStudentsCount: 40,
  },
  {
    id: 'course-2',
    name: 'Database Systems',
    code: 'CPE202',
    teacherId: 'user-teacher-1',
    teacherName: 'ดร. โรเบิร์ต แวนซ์',
    room: 'ห้อง 402',
    schedule: '13:00 - 16:00',
    enrolledStudentsCount: 42,
  },
  {
    id: 'course-3',
    name: 'Computer Networks',
    code: 'CPE303',
    teacherId: 'user-teacher-1',
    teacherName: 'ดร. โรเบิร์ต แวนซ์',
    room: 'ห้อง 205',
    schedule: '10:00 - 12:00',
    enrolledStudentsCount: 38,
  },
];

const today = new Date().toISOString().split('T')[0];

export const INITIAL_SESSIONS: AttendanceSession[] = [
  {
    id: 'session-101',
    courseId: 'course-1',
    courseName: 'Mobile Application Development',
    courseCode: 'CPE401',
    room: 'ห้อง 301',
    date: today,
    startTime: '09:00',
    endTime: '12:00',
    // Default university room coordinates (Khon Kaen Univ / general campus)
    latitude: 16.474431,
    longitude: 102.823101,
    allowedRadius: 50,
    status: 'open',
    totalExpected: 40,
    totalPresent: 34,
  },
  {
    id: 'session-102',
    courseId: 'course-2',
    courseName: 'Database Systems',
    courseCode: 'CPE202',
    room: 'ห้อง 402',
    date: today,
    startTime: '13:00',
    endTime: '16:00',
    latitude: 16.474500,
    longitude: 102.823500,
    allowedRadius: 50,
    status: 'closed',
    totalExpected: 42,
    totalPresent: 0,
  }
];

export const INITIAL_ATTENDANCE: Attendance[] = [
  {
    id: 'att-001',
    sessionId: 'session-prev-1',
    courseName: 'Mobile Application Development',
    courseCode: 'CPE401',
    room: 'ห้อง 301',
    studentId: 'user-student-1',
    studentName: 'นายสมชาย ใจดี',
    timestamp: new Date(Date.now() - 86400000 * 2).toISOString(),
    latitude: 16.474438,
    longitude: 102.823108,
    distanceFromClassroom: 23,
    gpsAccuracy: 8,
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80',
    status: 'present',
    verificationNotes: 'ตำแหน่งอยู่ในห้องเรียน แนบรูปถ่ายครบถ้วน เข้าเรียนตรงเวลา',
  },
  {
    id: 'att-002',
    sessionId: 'session-prev-2',
    courseName: 'Database Systems',
    courseCode: 'CPE202',
    room: 'ห้อง 402',
    studentId: 'user-student-1',
    studentName: 'นายสมชาย ใจดี',
    timestamp: new Date(Date.now() - 86400000 * 5).toISOString(),
    latitude: 16.474510,
    longitude: 102.823490,
    distanceFromClassroom: 15,
    gpsAccuracy: 6,
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80',
    status: 'present',
    verificationNotes: 'ตรวจสอบพิกัดและรูปถ่ายเรียบร้อย เข้าเรียนตามเวลา',
  },
  {
    id: 'att-003',
    sessionId: 'session-prev-3',
    courseName: 'Computer Networks',
    courseCode: 'CPE303',
    room: 'ห้อง 205',
    studentId: 'user-student-1',
    studentName: 'นายสมชาย ใจดี',
    timestamp: new Date(Date.now() - 86400000 * 7).toISOString(),
    latitude: 16.479000,
    longitude: 102.830000,
    distanceFromClassroom: 520,
    gpsAccuracy: 12,
    photoUrl: '',
    status: 'absent',
    verificationNotes: 'ไม่มีการส่งข้อมูลเช็กชื่อในคาบเรียนดังกล่าว',
  },
  {
    id: 'att-004',
    sessionId: 'session-prev-4',
    courseName: 'Software Engineering',
    courseCode: 'CPE304',
    room: 'ห้อง 303',
    studentId: 'user-student-1',
    studentName: 'นายสมชาย ใจดี',
    timestamp: new Date(Date.now() - 86400000 * 9).toISOString(),
    latitude: 16.474440,
    longitude: 102.823110,
    distanceFromClassroom: 31,
    gpsAccuracy: 7,
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80',
    status: 'late',
    verificationNotes: 'เช็กชื่อช้ากว่าเวลาเริ่มเรียน 17 นาที (มาสาย)',
  }
];
